### ISSUE TITLE
How to show multi-level headers?

### ISSUE THREAD

**Issue by yubaoliu** [ahungrynoob/showdown-toc#5]
How to show multi-level headers?

[toc]

like:

![image](https://user-images.githubusercontent.com/17697584/88885674-e8fa2100-d273-11ea-8eee-3b7e4e89efbd.png)

I see you show the example "use [toc] in each section"  in "output table of contents into your html string" section.

However, I did not see any example in your Readme to show how to use the multi-level headers.

You mensioned:

```sh
The toc array you pass in showdownToc will be:

[
    { anchor: 'header-1', level: 1, text: 'header 1' }, // # header 1
    { anchor: 'header-4', level: 4, text: 'header 4' }, // #### header 4
    ...
]
```

Whether you want to say if I want to use multi-level headers, I need to modify to:

```sh
The toc array you pass in showdownToc will be:

[
    { anchor: '#', level: 1, text: 'header 1' }, 
    { anchor: '##', level: 2, text: 'header 2' }, 
    ...
]
```
or sth. others.

Sorry, I cannot understand how to use to show multi-level table-of-contents list: e.g, 1, 1.1, 1.2 ; 2, 2.1, 2.2...

Thanks,

**Comment by ahungrynoob** [comment]
showdown-toc will collect all the headers into toc variable you passed, you can use that data to construct your logic and render them to html

**Comment by yubaoliu** [comment]
Sorry, I don't understand.

I use Markdown to write my source code and render to html use "showdown" JS script automatically.
The problem is that only the first level Header 1 ("#") is shown in toc now.

Could you explain "you can use that data to construct your logic and render them to html" in detail?
Thanks

**Comment by ahungrynoob** [comment]
Rendering as [toc] is just a fast and simple way to show table of content in html, for complex and advanced usage, you could use the data in toc variable you passed in this extension and write code to render the data of toc variable.

**Comment by yubaoliu** [comment]
You mean I need to customize this extension by myself? 
This function is not yet implemented in the current version?

**Comment by ahungrynoob** [comment]
different people meet with different table-of-content rendering requirement, this extension only provides the meta data of their markdown content, how to render the toc meta data is not this extension's business.

**Comment by yubaoliu** [comment]
I found this extention did not  provides the meta data of  markdown content. It can only works for "#" and "##" , "###" ... are not included in the TOC. I think this is the basic function. 
For example: https://python-markdown.github.io/extensions/toc/

```sh
[TOC]
# Header 1
## Header 2
```

The problem is  that " Header 2" is not shown in TOC using your extension. 

You said "how to render the toc meta data is not this extension's business". I guess I did not explain my question clearly. 
Sorry

I am not fully understand your response. Anyway, thanks for your kindly reply. 
Thanks

**Comment by ahungrynoob** [comment]
check readme, it's clear: https://github.com/ahungrynoob/showdown-toc#2-output-table-of-contents-into-your-html-string

**Comment by yubaoliu** [comment]
哈哈，又回到问题原点了。
实在看不出来，哪个地方有写？

**Comment by ahungrynoob** [comment]
If you move up a level from the headers being used for a [toc], the Table of Contents will stop (the assumption being you're "outside" of that section).

**Comment by ahungrynoob** [comment]
[toc] 只渲染当前作用域的目录，如果需要展示多级目录，属于自定义渲染需求，可以通过闭包传进去的参数 toc 进行渲染

**Comment by yubaoliu** [comment]
这个解释我终于能看懂了，谢谢。
那您的参数是什么？ 您说“通过闭包传进去的参数 toc 进行渲染”。
我要展示二级，三级标题的话，我应该如何传参？

**Comment by ahungrynoob** [comment]
```javascript
const toc = [];
const showdown = new Showdown.Converter({ extensions: [showdownToc({ toc })] });
```
这个 toc 变量你打印下就知道了，它会把所有header信息都收集到

**Comment by yubaoliu** [comment]
需要自己解析返回的 toc 变量来显示多级标题，是吧。 插件里没有这方面的处理，可以这么理解吧？

**Comment by ahungrynoob** [comment]
怎么展示属于业务定制需求，插件不作处理

**Comment by yubaoliu** [comment]
好像是有值，可能是有其它错误导致其不能显示：

![image](https://user-images.githubusercontent.com/17697584/88894197-793f6280-d282-11ea-91f0-bfc0e8f7c103.png)

![image](https://user-images.githubusercontent.com/17697584/88894397-c7546600-d282-11ea-8c8a-9392396f587a.png)

![image](https://user-images.githubusercontent.com/17697584/88894686-39c54600-d283-11ea-983e-fd4bd0e220ea.png)
